### ISSUE TITLE
您好，想请教一下

### ISSUE THREAD

**Issue by NoMindToThink** [charlotte-xiao/NCM2MP3-By-JAVA#19]
您好，我想请教一下，是如何知道ncm结构图的？

**Comment by charlotte-xiao** [comment]
It turned out that there was an analysis tool written in the cpp version of the `ncmdump`, which was written in imitation.
As for the structure diagram and private key, I personally speculate that the author of `ncmdump` got it after decompiling the official player client or analyzing the web page. Reason: 
1. The player must also parse the ncm format
2. Symmetric encryption, client decryption, so there must be a key in client
